SELECT Ename, Hire_date,
DATE_ADD(
DATE_ADD(Hire_date, INTERVAL 6 MONTH),
INTERVAL 9-DAYOFWEEK(
DATE_ADD(Hire_date, INTERVAL 6 MONTH)) DAY) 
AS 'Salary Review Date' FROM EMPLOYEE;

SELECT Ename, Hire_date,
DATE_ADD(DATE_ADD(Hire_date, INTERVAL 6 MONTH),
INTERVAL 9-DAYOFWEEK(DATE_ADD(Hire_date, INTERVAL 6 MONTH)) DAY) 
AS 'Salary Review Date',
DAYNAME(DATE_ADD(DATE_ADD(Hire_date, INTERVAL 6 MONTH),
INTERVAL 9-DAYOFWEEK(DATE_ADD(Hire_date, INTERVAL 6 MONTH)) DAY)) 
AS 'Day' FROM EMPLOYEE;

SELECT Ename, Hire_date,
DATE_ADD(Hire_date, INTERVAL 6 MONTH) 
AS 'Salary Review Date',
DAYOFWEEK(DATE_ADD(Hire_date, INTERVAL 6 MONTH))
AS 'Day' FROM EMPLOYEE;

SELECT Ename, Hire_date,
IF(DAYOFWEEK(DATE_ADD(Hire_date, INTERVAL 6 MONTH))=2,
	DATE_ADD(Hire_date, INTERVAL 6 MONTH),
	DATE_ADD(DATE_ADD(Hire_date, INTERVAL 6 MONTH),
		INTERVAL 9-DAYOFWEEK(
			DATE_ADD(Hire_date, INTERVAL 6 MONTH)) DAY) 
) AS 'Salary Review Date' FROM EMPLOYEE;

SELECT Ename, Hire_date,
IF(DAYOFWEEK(DATE_ADD(Hire_date, INTERVAL 6 MONTH))=2,
	DATE_ADD(Hire_date, INTERVAL 6 MONTH),
	DATE_ADD(DATE_ADD(Hire_date, INTERVAL 6 MONTH),
		INTERVAL 9-DAYOFWEEK(
			DATE_ADD(Hire_date, INTERVAL 6 MONTH)) DAY) 
) AS 'Salary Review Date', DAYNAME(
	IF(DAYOFWEEK(DATE_ADD(Hire_date, INTERVAL 6 MONTH))=2,
		DATE_ADD(Hire_date, INTERVAL 6 MONTH),
		DATE_ADD(DATE_ADD(Hire_date, INTERVAL 6 MONTH),
			INTERVAL 9-DAYOFWEEK(
				DATE_ADD(Hire_date, INTERVAL 6 MONTH)) DAY) 
	)) AS 'Day' FROM EMPLOYEE;