CREATE SCHEMA COMPANY;
USE COMPANY;
CREATE TABLE EMPLOYEE
(Eno CHAR(3) NOT NULL,
Ename VARCHAR(50) NOT NULL,
Job_type VARCHAR(50) NOT NULL,
SupervisonENO CHAR(3),
Hire_date DATE NOT NULL,
Dno INTEGER,
Commission DECIMAL(10,2),
Salary DECIMAL(7,2) NOT NULL,
PRIMARY KEY(Eno));

CREATE TABLE DEPARTMENT
(Dno INTEGER NOT NULL,
Dname VARCHAR(50) DEFAULT NULL,
Location VARCHAR(50) DEFAULT 'New Delhi',
PRIMARY KEY(Dno));

# Adding Dno as Foreign key in EMPLOYEE
ALTER TABLE EMPLOYEE
ADD FOREIGN KEY(Dno)
REFERENCES DEPARTMENT(Dno);

# Adding Manager as Foreign key in EMPLOYEE table
ALTER TABLE EMPLOYEE
ADD FOREIGN KEY(SupervisonENO)
REFERENCES EMPLOYEE(Eno);

DESCRIBE EMPLOYEE;
DESCRIBE DEPARTMENT;
SHOW CREATE TABLE EMPLOYEE;